# Generated by Django 2.2.4 on 2019-09-25 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2LazyCatalog',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp2_importer_id', models.CharField(max_length=255)),
                ('pulp2_unit_id', models.CharField(max_length=255)),
                ('pulp2_content_type_id', models.CharField(max_length=255)),
                ('pulp2_storage_path', models.TextField()),
                ('pulp2_url', models.TextField()),
                ('pulp2_revision', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('pulp2_storage_path', 'pulp2_importer_id', 'pulp2_revision')},
            },
        ),
    ]
