# Generated by Django 2.2.9 on 2020-02-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulp2distributor',
            name='pulp2_auto_publish',
        ),
    ]
