# Generated by Django 2.2.4 on 2019-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulp2distributor',
            name='pulp2_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pulp2iso',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pulp2repository',
            name='pulp2_repo_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pulp2tag',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pulp2tag',
            name='repo_id',
            field=models.TextField(),
        ),
    ]
