# Generated by Django 2.2.9 on 2020-02-14 10:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0002_remove_pulp2distributor_pulp2_auto_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2Erratum',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('errata_id', models.TextField(unique=True)),
                ('updated', models.TextField()),
                ('issued', models.TextField()),
                ('status', models.TextField()),
                ('description', models.TextField()),
                ('pushcount', models.TextField()),
                ('references', django.contrib.postgres.fields.jsonb.JSONField()),
                ('reboot_suggested', models.BooleanField()),
                ('relogin_suggested', models.BooleanField()),
                ('restart_suggested', models.BooleanField()),
                ('errata_from', models.TextField()),
                ('severity', models.TextField()),
                ('rights', models.TextField()),
                ('version', models.TextField()),
                ('release', models.TextField()),
                ('errata_type', models.TextField()),
                ('pkglist', django.contrib.postgres.fields.jsonb.JSONField()),
                ('title', models.TextField()),
                ('solution', models.TextField()),
                ('summary', models.TextField()),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erratum_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'erratum_detail_model',
            },
        ),
        migrations.CreateModel(
            name='Pulp2Rpm',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('epoch', models.TextField()),
                ('version', models.TextField()),
                ('release', models.TextField()),
                ('arch', models.TextField()),
                ('checksum', models.TextField()),
                ('checksumtype', models.TextField()),
                ('repodata', django.contrib.postgres.fields.jsonb.JSONField(verbose_name=dict)),
                ('is_modular', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField()),
                ('filename', models.TextField()),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpm_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'rpm_detail_model',
                'unique_together': {('name', 'epoch', 'version', 'release', 'arch', 'checksumtype', 'checksum', 'pulp2content')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pulp2manifest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pulp2manifest',
            name='pulp2content',
        ),
        migrations.AlterUniqueTogether(
            name='pulp2manifestlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pulp2manifestlist',
            name='pulp2content',
        ),
        migrations.AlterUniqueTogether(
            name='pulp2tag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pulp2tag',
            name='pulp2content',
        ),
        migrations.DeleteModel(
            name='Pulp2Blob',
        ),
        migrations.DeleteModel(
            name='Pulp2Manifest',
        ),
        migrations.DeleteModel(
            name='Pulp2ManifestList',
        ),
        migrations.DeleteModel(
            name='Pulp2Tag',
        ),
    ]
