# Generated by Django 2.2.6 on 2019-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0002_auto_20191030_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulp2distributor',
            name='not_in_pulp2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pulp2importer',
            name='not_in_pulp2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pulp2repository',
            name='not_in_pulp2',
            field=models.BooleanField(default=False),
        ),
    ]
