# Generated by Django 2.2.4 on 2019-10-02 16:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0002_pulp2lazycatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2Tag',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('tagged_manifest', models.CharField(max_length=255)),
                ('repo_id', models.CharField(max_length=255)),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_tag_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'docker_tag_detail_model',
                'unique_together': {('name', 'tagged_manifest', 'repo_id', 'pulp2content')},
            },
        ),
        migrations.CreateModel(
            name='Pulp2ManifestList',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('digest', models.CharField(max_length=255)),
                ('schema_version', models.IntegerField()),
                ('media_type', models.CharField(max_length=80)),
                ('listed_manifests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_manifest_list_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'docker_manifest_list_detail_model',
                'unique_together': {('digest', 'pulp2content')},
            },
        ),
        migrations.CreateModel(
            name='Pulp2Manifest',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('digest', models.CharField(max_length=255)),
                ('schema_version', models.IntegerField()),
                ('media_type', models.CharField(max_length=80)),
                ('blobs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('config_blob', models.CharField(max_length=255, null=True)),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_manifest_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'docker_manifest_detail_model',
                'unique_together': {('digest', 'pulp2content')},
            },
        ),
        migrations.CreateModel(
            name='Pulp2Blob',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('digest', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=80)),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_blob_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'docker_blob_detail_model',
                'unique_together': {('digest', 'pulp2content')},
            },
        ),
    ]
