# Generated by Django 2.2.8 on 2019-12-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191127_2350'),
        ('pulp_2to3_migration', '0002_auto_20191206_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulp2repository',
            name='pulp3_repository_remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Remote'),
        ),
    ]
