# Generated by Django 2.2.9 on 2020-01-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0002_auto_20200130_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2GlobalImporterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(max_length=255)),
                ('proxy_url', models.TextField(null=True)),
                ('proxy_port', models.IntegerField(null=True)),
                ('proxy_username', models.TextField(null=True)),
                ('proxy_password', models.TextField(null=True)),
                ('connect_timeout', models.FloatField(null=True)),
                ('read_timeout', models.IntegerField(null=True)),
            ],
        ),
    ]
