# Generated by Django 2.2.10 on 2020-03-10 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0003_pulp2erratum_pulp2rpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2YumRepoMetadataFile',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('data_type', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=128)),
                ('checksum_type', models.CharField(max_length=6)),
                ('repo_id', models.TextField()),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yum_repo_metadata_file_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'yum_repo_metadata_file_detail_model',
                'unique_together': {('data_type', 'repo_id', 'pulp2content')},
            },
        ),
    ]
