# Generated by Django 2.2.10 on 2020-03-13 19:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0004_pulp2yumrepometadatafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2ModulemdDefaults',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.TextField()),
                ('stream', models.TextField()),
                ('profiles', django.contrib.postgres.fields.jsonb.JSONField(verbose_name=dict)),
                ('digest', models.TextField()),
                ('repo_id', models.TextField()),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulemd_defaults_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'modulemd_defaults_detail_model',
                'unique_together': {('digest', 'repo_id', 'pulp2content')},
            },
        ),
        migrations.CreateModel(
            name='Pulp2Modulemd',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('stream', models.TextField()),
                ('version', models.BigIntegerField()),
                ('context', models.TextField()),
                ('arch', models.TextField()),
                ('artifacts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('checksum', models.TextField()),
                ('dependencies', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulemd_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'modulemd_detail_model',
                'unique_together': {('name', 'stream', 'version', 'context', 'arch', 'pulp2content')},
            },
        ),
    ]
