# Generated by Django 2.2.11 on 2020-04-09 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_task_group'),
        ('pulp_2to3_migration', '0006_pulp2_comps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulp2repository',
            name='pulp3_repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Repository'),
        ),
    ]
