# Generated by Django 2.2.12 on 2020-04-17 16:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0007_pulp2repository_pulp3_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2Srpm',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('epoch', models.TextField()),
                ('version', models.TextField()),
                ('release', models.TextField()),
                ('arch', models.TextField()),
                ('checksum', models.TextField()),
                ('checksumtype', models.TextField()),
                ('repodata', django.contrib.postgres.fields.jsonb.JSONField(verbose_name=dict)),
                ('is_modular', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField()),
                ('filename', models.TextField()),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srpm_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'srpm_detail_model',
                'unique_together': {('name', 'epoch', 'version', 'release', 'arch', 'checksumtype', 'checksum', 'pulp2content')},
            },
        ),
    ]
