# Generated by Django 2.2.12 on 2020-06-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0011_lce_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulp2rpm',
            name='size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pulp2srpm',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
