# Generated by Django 2.2.14 on 2020-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0014_gzip_repodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulp2repocontent',
            name='pulp2_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pulp2repocontent',
            name='pulp2_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
