# Generated by Django 2.2.17 on 2020-11-16 15:33

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0016_type_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp2DebPackage',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('checksumtype', models.TextField()),
                ('checksum', models.TextField()),
                ('filename', models.TextField()),
                ('size', models.BigIntegerField()),
                ('extra_control_fields', models.TextField(null=True)),
                ('package', models.TextField()),
                ('source', models.TextField(null=True)),
                ('version', models.TextField()),
                ('essential', models.TextField(null=True)),
                ('installed_size', models.TextField(null=True)),
                ('maintainer', models.TextField(null=True)),
                ('original_maintainer', models.TextField(null=True)),
                ('architecture', models.TextField()),
                ('replaces', models.TextField(null=True)),
                ('provides', models.TextField(null=True)),
                ('depends', models.TextField(null=True)),
                ('pre_depends', models.TextField(null=True)),
                ('recommends', models.TextField(null=True)),
                ('suggests', models.TextField(null=True)),
                ('enhances', models.TextField(null=True)),
                ('conflicts', models.TextField(null=True)),
                ('breaks', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('multi_arch', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('built_using', models.TextField(null=True)),
                ('description_md5', models.TextField(null=True)),
                ('build_essential', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('section', models.TextField(null=True)),
                ('priority', models.TextField(null=True)),
                ('pulp2content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_detail_model', to='pulp_2to3_migration.Pulp2Content')),
            ],
            options={
                'default_related_name': 'deb_detail_model',
                'unique_together': {('package', 'version', 'architecture', 'checksumtype', 'checksum', 'pulp2content')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
