# Generated by Django 2.2.17 on 2021-01-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_2to3_migration', '0020_fix_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulp2content',
            name='pulp2_subid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pulp2content',
            unique_together={('pulp2_id', 'pulp2_content_type_id', 'pulp2_repo', 'pulp2_subid')},
        ),
    ]
