# Generated by Django 2.2.20 on 2021-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulp_2to3_migration", "0030_update_json_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulp2debcomponent",
            name="repoid",
            field=models.TextField(default="blub"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pulp2debrelease",
            name="repoid",
            field=models.TextField(default="blub"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pulp2debcomponentpackage",
            name="repoid",
            field=models.TextField(default="blub"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pulp2debreleasearchitecture",
            name="repoid",
            field=models.TextField(default="blub"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="pulp2debcomponent",
            unique_together={
                ("component", "codename", "suite", "distribution", "repoid")
            },
        ),
        migrations.AlterUniqueTogether(
            name="pulp2debrelease",
            unique_together={("codename", "suite", "distribution", "repoid")},
        ),
        migrations.AlterUniqueTogether(
            name="pulp2debcomponentpackage",
            unique_together={
                (
                    "package_relative_path",
                    "package_sha256",
                    "component",
                    "distribution",
                    "codename",
                    "suite",
                    "repoid",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="pulp2debreleasearchitecture",
            unique_together={
                ("architecture", "distribution", "codename", "suite", "repoid")
            },
        ),
    ]
